// NOTE: team keys, ids and player names are case sensitive

export const pickOrder = [
  // indexes, see below
  0, 1, 2, 3, 4, 5, 6,
  0, 1, 2, 3, 4, 5, 6,
  6, 5, 4, 3, 2, 1, 0,
];

export const teams = {
  Baresi: {
    id: "Baresi",
    playerNames: ["Baresi"],
    index: 6,
  },
  TiMMi: {
    id: "TiMMi",
    playerNames: ["TiMMi"],
    index: 5,
  },
  Thunder: {
    id: "Thunder",
    playerNames: ["Thunder"],
    index: 4,
  },
  paniagua: {
    id: "paniagua",
    playerNames: ["paniagua"],
    index: 3,
  },
  coj: {
    id: "coj",
    playerNames: ["coj"],
    index: 2,
  },
  Flamer: {
    id: "Flamer",
    playerNames: ["Flamer"],
    index: 1,
  },
  Hooraytio: {
    id: "Hooraytio",
    playerNames: ["Hooraytio"],
    index: 0,
  },
};

const Player = (name, country_code) => ({ name, country_code });

export const players = {
  "anni": Player("anni", "de"),
  "badsebi": Player("badsebi", "pl"),
  "Baresi": Player("Baresi", "no"),
  "BTK": Player("BTK", "ru"),
  "Calinou": Player("Calinou", "fr"),
  "coj": Player("coj", "us"),
  "cor": Player("cor", "pl"),
  "devil": Player(".devil", "ru"),
  "dib": Player("dib", "pt"),
  "diehuman": Player("diehuman", "pt"),
  "dobez": Player("dobez", "_scotland"),
  "driz": Player("driz", "us"),
  "Effie": Player("Effie", "no"),
  "eizor": Player("eizor", "de"),
  "Ekz": Player("Ekz", "se"),
  "eppe": Player("eppe", "se"),
  "FagFrager": Player("FagFrager", "pl"),
  "Final": Player("Final", "mt"),
  "Flamer": Player("Flamer", "cz"),
  "floc": Player("floc", "de"),
  "HaraldQuake": Player("HaraldQuake", "de"),
  "himmu": Player("himmu", "fi"),
  "Hooraytio": Player("Hooraytio", "se"),
  "Karnage": Player("Karnage", "us"),
  "kinoko": Player("kinoko", "ee"),
  "kip": Player("kip", "fi"),
  "Klice": Player("Klice", "fr"),
  "knasty": Player("knasty", "de"),
  "lethalwiz": Player("lethalwiz", "se"),
  "Link": Player("Link", "no"),
  "Lucky": Player("Lucky", "fi"),
  "MolkyPolky": Player("MolkyPolky", "ua"),
  "mushi": Player("mushi", "pt"),
  "ncr": Player("ncr", "se"),
  "Neopite": Player("Neopite", "hu"),
  "nexus": Player("nexus", "fi"),
  "Nico": Player("Nico", "us"),
  "Nidweyr": Player("Nidweyr", "de"),
  "Nilton": Player("Nilton", "cz"),
  "oho": Player("oho", "fi"),
  "paniagua": Player("paniagua", "fi"),
  "pattah": Player("pattah", "de"),
  "Pitbull": Player("Pitbull", "lt"),
  "pixols": Player("pixols", "gb"),
  "ponczek": Player("ponczek", "pl"),
  "pooll": Player("pooll", "pl"),
  "PreMorteM": Player("PreMorteM", "no"),
  "rat": Player("rat", "fi"),
  "rghst": Player("rghst", "de"),
  "Riki": Player("Riki", "pl"),
  "rotker": Player("rotker", "pl"),
  "rusti": Player("rusti", "fi"),
  "samon": Player("samon", "pl"),
  "Shining": Player("Shining", "se"),
  "Si7H": Player("Si7H", "pl"),
  "skurk": Player("skurk", "se"),
  "Slaughter": Player("Slaughter", "fi"),
  "splif": Player("splif", "ie"),
  "Thunder": Player("Thunder", "pl"),
  "TiMMi": Player("TiMMi", "no"),
  "tr0ll": Player("tr0ll", "no"),
  "Viag": Player("Viag", "ca"),
  "Zalon": Player("Zalon", "dk"),
  "zigg": Player("zigg", "gb")
}
