/*
index team
6     Milton
5     bps
4     ParadokS
3     zero
2     razor
1     Diki
0     Gamer
*/

export const pickOrder = [
  // div 1 players
  0, 1, 2, 3, 4, 5, 6,
  0, 1, 2, 3, 4, 5, 6,
  6, 5, 4, 3, 2, 1, 0,
];

export const teams = {
  Milton: {
    id: "Milton",
    playerNames: ["Milton"],
    sortOrder: 7,
  },
  bps: {
    id: "bps",
    playerNames: ["bps"],
    sortOrder: 6,
  },
  ParadokS: {
    id: "ParadokS",
    playerNames: ["ParadokS"],
    sortOrder: 5,
  },
  zero: {
    id: "zero",
    playerNames: ["zero"],
    sortOrder: 4,
  },
  razor: {
    id: "razor",
    playerNames: ["razor"],
    sortOrder: 3,
  },
  Diki: {
    id: "Diki",
    playerNames: ["Diki"],
    sortOrder: 2,
  },
  Gamer: {
    id: "Gamer",
    playerNames: ["Gamer"],
    sortOrder: 1,
  },
};

export const players = {
  "AiRman": { "name": "AiRman", "country_code": "pl" },
  "Andeh": { "name": "Andeh", "country_code": "se" },
  "anni": { "name": "anni", "country_code": "de" },
  "badsebi": { "name": "badsebi", "country_code": "pl" },
  "Baresi": { "name": "Baresi", "country_code": "no" },
  "bps": { "name": "bps", "country_code": "se" },
  "BTK": { "name": "BTK", "country_code": "ru" },
  "Calinou": { "name": "Calinou", "country_code": "fr" },
  "coj": { "name": "coj", "country_code": "us" },
  "cor": { "name": "cor", "country_code": "pl" },
  "Creature": { "name": "Creature", "country_code": "fi" },
  "dev": { "name": "dev", "country_code": "es" },
  "devil": { "name": ".devil", "country_code": "ru" },
  "dib": { "name": "dib", "country_code": "pt" },
  "diehuman": { "name": "diehuman", "country_code": "pt" },
  "Diki": { "name": "Diki", "country_code": "fi" },
  "dobez": { "name": "dobez", "country_code": "_scotland" },
  "driz": { "name": "driz", "country_code": "us" },
  "Effie": { "name": "Effie", "country_code": "no" },
  "eizor": { "name": "eizor", "country_code": "de" },
  "eppe": { "name": "eppe", "country_code": "se" },
  "FagFrager": { "name": "FagFrager", "country_code": "pl" },
  "Final": { "name": "Final", "country_code": "mt" },
  "fix": { "name": "fix", "country_code": "fi" },
  "Flamer": { "name": "Flamer", "country_code": "cz" },
  "floc": { "name": "floc", "country_code": "de" },
  "Gamer": { "name": "Gamer", "country_code": "fi" },
  "goblin": { "name": "goblin", "country_code": "se" },
  "gor": { "name": "gor", "country_code": "ru" },
  "Grc": { "name": "Grc", "country_code": "se" },
  "HangTine": { "name": "HangTine", "country_code": "gb" },
  "HaraldQuake": { "name": "HaraldQuake", "country_code": "de" },
  "himmu": { "name": "himmu", "country_code": "fi" },
  "Hooraytio": { "name": "Hooraytio", "country_code": "se" },
  "kinoko": { "name": "kinoko", "country_code": "ee" },
  "kip": { "name": "kip", "country_code": "fi" },
  "Klice": { "name": "Klice", "country_code": "fr" },
  "knasty": { "name": "knasty", "country_code": "de" },
  "lethalwiz": { "name": "lethalwiz", "country_code": "se" },
  "Link": { "name": "Link", "country_code": "no" },
  "Lucky": { "name": "Lucky", "country_code": "fi" },
  "Macler": { "name": "Macler", "country_code": "pl" },
  "Medic": { "name": "Medic", "country_code": "se" },
  "Milton": { "name": "Milton", "country_code": "fi" },
  "MolkyPolky": { "name": "MolkyPolky", "country_code": "ua" },
  "mushi": { "name": "mushi", "country_code": "pt" },
  "ncr": { "name": "ncr", "country_code": "se" },
  "Neopite": { "name": "Neopite", "country_code": "hu" },
  "nexus": { "name": "nexus", "country_code": "fi" },
  "Nico": { "name": "Nico", "country_code": "us" },
  "Nidweyr": { "name": "Nidweyr", "country_code": "de" },
  "Nigve": { "name": "Nigve", "country_code": "no" },
  "Nilton": { "name": "Nilton", "country_code": "cz" },
  "niw": { "name": "niw", "country_code": "dk" },
  "oho": { "name": "oho", "country_code": "fi" },
  "Ok98": { "name": "Ok98", "country_code": "se" },
  "overflow": { "name": "overflow", "country_code": "ch" },
  "paniagua": { "name": "paniagua", "country_code": "fi" },
  "ParadokS": { "name": "ParadokS", "country_code": "dk" },
  "pattah": { "name": "pattah", "country_code": "de" },
  "ponczek": { "name": "ponczek", "country_code": "pl" },
  "pooll": { "name": "pooll", "country_code": "pl" },
  "PreMorteM": { "name": "PreMorteM", "country_code": "no" },
  "raket": { "name": "raket", "country_code": "se" },
  "razor": { "name": "razor", "country_code": "se" },
  "rghst": { "name": "rghst", "country_code": "de" },
  "Riki": { "name": "Riki", "country_code": "pl" },
  "RIO": { "name": "RIO", "country_code": "se" },
  "rotker": { "name": "rotker", "country_code": "pl" },
  "rst": { "name": "rst", "country_code": "se" },
  "rusti": { "name": "rusti", "country_code": "fi" },
  "sae": { "name": "sae", "country_code": "gb" },
  "samon": { "name": "samon", "country_code": "pl" },
  "ShaZm": { "name": "ShaZm", "country_code": "se" },
  "Shining": { "name": "Shining", "country_code": "se" },
  "Si7H": { "name": "Si7H", "country_code": "pl" },
  "skurk": { "name": "skurk", "country_code": "se" },
  "Slaughter": { "name": "Slaughter", "country_code": "fi" },
  "Sniegov": { "name": "Sniegov", "country_code": "pl" },
  "splif": { "name": "splif", "country_code": "ie" },
  "TheChosenOne": { "name": "TheChosenOne", "country_code": "no" },
  "Thunder": { "name": "Thunder", "country_code": "pl" },
  "TiMMi": { "name": "TiMMi", "country_code": "no" },
  "Tom": { "name": "Tom", "country_code": "pl" },
  "tr0ll": { "name": "tr0ll", "country_code": "no" },
  "Viag": { "name": "Viag", "country_code": "ca" },
  "Wim": { "name": "Wim", "country_code": "nl" },
  "Zalon": { "name": "Zalon", "country_code": "dk" },
  "zero": { "name": "zero", "country_code": "hu" },
  "zigg": { "name": "zigg", "country_code": "gb" }
};
