export const teams = {
  777: {
    id: "777",
    name: "777",
    playerNames: [],
    theme: "777",
    sortOrder: 1,
  },
  666: {
    id: "666",
    name: "666",
    playerNames: [],
    theme: "666",
    sortOrder: 2,
  },
};

export const players = {
  XantoM: { name: "XantoM", country_code: "se" },
  bps: { name: "bps", country_code: "se" },
  Milton: { name: "Milton", country_code: "fi" },
  henu: { name: "henu", country_code: "fi" },
  mm: { name: "mm", country_code: "se" },
  HangTime: { name: "HangTime", country_code: "gb" },
  lordlame: { name: "lordlame", country_code: "ie" },
  ok98: { name: "ok98", country_code: "se" },
  ParadokS: { name: "ParadokS", country_code: "dk" },
  Shaka: { name: "Shaka", country_code: "se" },
  Shaka1: { name: "Shaka1", country_code: "se" },
  Shaka2: { name: "Shaka2", country_code: "se" },
  Shaka3: { name: "Shaka3", country_code: "se" },
  Shaka4: { name: "Shaka4", country_code: "se" },
  Shaka5: { name: "Shaka5", country_code: "se" },
  Shaka6: { name: "Shaka6", country_code: "se" },
  Shaka7: { name: "Shaka7", country_code: "se" },
  Shaka8: { name: "Shaka8", country_code: "se" },
  Shaka9: { name: "Shaka9", country_code: "se" },
  Shaka10: { name: "Shaka10", country_code: "se" },
  Shaka11: { name: "Shaka11", country_code: "se" },
  Shaka12: { name: "Shaka12", country_code: "se" },
  Shaka13: { name: "Shaka13", country_code: "se" },
  Shaka14: { name: "Shaka14", country_code: "se" },
};
